# Bug Report Template for Tiny11 Automated
# Author: kelexine
# GitHub: https://github.com/kelexine/tiny11-automated

name: 🐛 Bug Report
description: Report a bug or issue with Tiny11 Auto-Builder
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - kelexine

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug! 🐛
        
        Please fill out this form completely to help us fix the issue quickly.
        
        **Before submitting:**
        - Search existing issues to avoid duplicates
        - Check if you're using the latest release
        - Verify your system meets requirements
        
        ---

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I searched existing issues and found no duplicates
          required: true
        - label: I'm using the latest release from GitHub or SourceForge
          required: true
        - label: I've read the README and documentation
          required: true
        - label: This is not a security vulnerability (use SECURITY.md for those)
          required: true

  - type: dropdown
    id: variant
    attributes:
      label: Build Variant
      description: Which Tiny11 variant are you using?
      options:
        - Tiny11 Standard
        - Tiny11 Core
        - Nano11
        - Not sure / Multiple
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Tiny11 Version
      description: "Example: tiny11-25H2-2025-12-24"
      placeholder: "tiny11-XXX-YYYY-MM-DD"
    validations:
      required: true

  - type: dropdown
    id: windows_edition
    attributes:
      label: Windows Edition
      description: Which Windows 11 edition did you build?
      options:
        - Home
        - Pro
        - Pro N
        - Education
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the ISO to..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, the build..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Download ISO from...
        2. Run script with parameters...
        3. Observe error at stage...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Build Environment
      description: Where did the build occur?
      options:
        - GitHub Actions (automated)
        - Local Windows 10
        - Local Windows 11
        - Virtual Machine
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Provide details about your build environment
      placeholder: |
        OS: Windows 11 Pro 23H2
        PowerShell: 5.1.22621.2506
        RAM: 16GB
        Free Disk Space: 50GB
        ISO Source: Microsoft Download
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Paste relevant error messages or logs
      placeholder: |
        Copy and paste any error messages here.
        Include timestamps if available.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if they help explain the issue
      placeholder: "Drag and drop images here"
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: How Often Does This Happen?
      description: Is this reproducible?
      options:
        - Always (100% of the time)
        - Frequently (more than 50%)
        - Sometimes (less than 50%)
        - Rarely (happened once or twice)
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact Severity
      description: How does this affect your usage?
      options:
        - Critical - Blocks all usage
        - High - Major feature broken
        - Medium - Workaround exists
        - Low - Minor inconvenience
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Have you found a temporary solution?
      placeholder: "I was able to work around this by..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "This started happening after..., I also noticed that..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this?
      options:
        - label: I can submit a PR to fix this
        - label: I can help test a fix
        - label: I can provide more information if needed

  - type: markdown
    attributes:
      value: |
        ---
        
        ## What Happens Next?
        
        1. **Triage** (24-48h): kelexine will review and label your issue
        2. **Investigation** (3-7 days): We'll investigate and may ask for more info
        3. **Fix** (varies): Depending on complexity, a fix will be developed
        4. **Release** (next release): Fix included in next version
        
        **Thank you for helping improve Tiny11 Automated!** 🙏
