# Feature Request Template for Tiny11 Automated
# Author: kelexine
# GitHub: https://github.com/kelexine/tiny11-automated

name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
assignees:
  - kelexine

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! ✨
        
        Your ideas help make Tiny11 better for 2,000+ users worldwide.
        
        **Before submitting:**
        - Search existing feature requests to avoid duplicates
        - Consider if this fits the project scope
        - Think about impact on existing users
        
        ---

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I searched existing issues and found no duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I've considered the impact on existing functionality
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Build Variant (e.g., Tiny11 Server)
        - Script Enhancement
        - CI/CD Improvement
        - Documentation
        - User Interface / GUI
        - Performance Optimization
        - Testing / Quality Assurance
        - Security Enhancement
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, users struggle with...
        This causes frustration because...
        It would be better if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: |
        I propose adding a feature that...
        This would work by...
        Users could then...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: |
        Alternative 1: We could instead...
        Alternative 2: Another option is...
        I prefer the main solution because...
    validations:
      required: false

  - type: dropdown
    id: users_affected
    attributes:
      label: Who Would Benefit?
      description: How many users would use this feature?
      options:
        - Everyone (all users)
        - Most users (>75%)
        - Many users (50-75%)
        - Some users (25-50%)
        - Few users (<25%)
        - Specific use case only
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this to you?
      options:
        - Critical - Blocking my usage
        - High - Would greatly improve experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this would be useful
      placeholder: |
        Use Case 1: A user wants to...
        Use Case 2: An organization needs to...
        Use Case 3: Power users could...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Projects
      description: Have you seen this feature elsewhere?
      placeholder: |
        Project X implements this by...
        Tool Y has a similar feature that...
        This approach works well because...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Technical details or suggestions (optional)
      placeholder: |
        This could be implemented by:
        1. Adding a new parameter...
        2. Modifying the function...
        3. Creating a new module...
        
        Potential challenges:
        - Challenge 1
        - Challenge 2
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes?
      options:
        - No - Fully backward compatible
        - Minor - Small changes to existing behavior
        - Major - Significant changes required
        - Unknown
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Impact
      description: What documentation would need updating?
      placeholder: |
        - README.md: Add new section on...
        - CONTRIBUTING.md: Update build instructions
        - New guide: Create tutorial for...
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing Considerations
      description: How should this feature be tested?
      placeholder: |
        - Unit tests for...
        - Integration tests for...
        - Manual testing steps...
    validations:
      required: false

  - type: dropdown
    id: difficulty
    attributes:
      label: Estimated Complexity
      description: How complex do you think this is?
      options:
        - Trivial - Few lines of code
        - Easy - A few hours of work
        - Medium - A few days of work
        - Hard - A week or more
        - Very Hard - Major undertaking
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help implement this?
      options:
        - label: I can implement this feature myself
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide design/mockups
        - label: I can provide funding/sponsorship

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Diagrams
      description: Visual representation (if applicable)
      placeholder: "Drag and drop images, diagrams, or mockups here"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "Related issues: #123, #456..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Decision Process
        
        Feature requests go through this process:
        
        1. **Community Discussion** (1-2 weeks): Gather feedback
        2. **Maintainer Review**: Evaluate feasibility and alignment
        3. **Decision**: Accept, defer, or decline with reasoning
        4. **Implementation**: If accepted, added to roadmap
        
        **Note:** Not all features can be accepted due to:
        - Scope limitations
        - Maintenance burden
        - Complexity vs. benefit
        - Resource constraints
        
        **Thank you for helping shape Tiny11's future!** 🚀
